version: "3.9"

services:


  keycloak: 
    build: Keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
  
  mysql:
    image: mysql:8.0.30
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: keycloak
    volumes:
      - mysql-data:/var/lib/mysql
      - ./MySQL:/docker-entrypoint-initdb.d

# Backend is Disabled due to for demo purposes. Refer to the readme file on github
#  backend: 
#    build: /Backend
#    depends_on:
#      - mysql
#    ports:
#      - "8090:8090"
#    links: 
#      - mysql
#    volumes:
#      - ./Backend/uploads:/uploads

volumes:
  mysql-data: